// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBT2tEsvNO5AIGLFkjz-5KHL0kjFJ6JBiY',
    appId: '1:14143379024:web:d00beaa132edbc9e7e2355',
    messagingSenderId: '14143379024',
    projectId: 'aqar360-app-b32e5',
    authDomain: 'aqar360-app-b32e5.firebaseapp.com',
    storageBucket: 'aqar360-app-b32e5.firebasestorage.app',
    measurementId: 'G-LYGYPZNX6X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeU09q-QVFHHVZ7APRz_IEKMEOxCHfMmU',
    appId: '1:14143379024:android:d18c4268a37061f77e2355',
    messagingSenderId: '14143379024',
    projectId: 'aqar360-app-b32e5',
    storageBucket: 'aqar360-app-b32e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj7dy3tDWU-7GDqoRudMveBgkiG9RlapA',
    appId: '1:14143379024:ios:03762edcecd539077e2355',
    messagingSenderId: '14143379024',
    projectId: 'aqar360-app-b32e5',
    storageBucket: 'aqar360-app-b32e5.firebasestorage.app',
    iosBundleId: 'com.example.aqar360',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj7dy3tDWU-7GDqoRudMveBgkiG9RlapA',
    appId: '1:14143379024:ios:03762edcecd539077e2355',
    messagingSenderId: '14143379024',
    projectId: 'aqar360-app-b32e5',
    storageBucket: 'aqar360-app-b32e5.firebasestorage.app',
    iosBundleId: 'com.example.aqar360',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBT2tEsvNO5AIGLFkjz-5KHL0kjFJ6JBiY',
    appId: '1:14143379024:web:25ff429213628bf57e2355',
    messagingSenderId: '14143379024',
    projectId: 'aqar360-app-b32e5',
    authDomain: 'aqar360-app-b32e5.firebaseapp.com',
    storageBucket: 'aqar360-app-b32e5.firebasestorage.app',
    measurementId: 'G-S6EHSKDV7H',
  );
}
