import 'package:aqar360/app/features/addProperty/data/models/apartment_details.dart';
import 'package:aqar360/app/features/addProperty/data/models/land_details.dart';
import 'package:aqar360/app/features/addProperty/data/models/villa_details.dart';

class AppListProperty {
  static List<VillaDetails> villas = [
    VillaDetails(
      title: "فيلا في الحي السادس",
      imagesUrl: ["https://cdn.britannica.com/05/157305-004-53D5D212.jpg"],
      area: 450,
      price: 3500000,
      location: "العاشر من رمضان",
      isForSale: true,
      isFavorite: false,
      bedrooms: 4,
      bathrooms: 3,
      livingRooms: 2,
      floors: 3,
      hasPool: true,
      hasGarden: true,
      hasGarage: true,
    ),
    VillaDetails(
      title: "فيلا دوبلكس فاخرة",
      imagesUrl: ["https://cdn.britannica.com/05/157305-004-53D5D212.jpg"],
      area: 600,
      price: 5000000,
      location: "الحي الثامن",
      isForSale: false,
      isFavorite: true,
      bedrooms: 5,
      bathrooms: 4,
      livingRooms: 3,
      floors: 2,
      hasPool: false,
      hasGarden: true,
      hasGarage: true,
    ),
  ];

  static List<ApartmentDetails> apartments = [
    ApartmentDetails(
      title: "شقة 3 غرف بإطلالة رائعة",
      imagesUrl: ["https://cdn.britannica.com/05/157305-004-53D5D212.jpg"],
      area: 180,
      price: 1200000,
      location: "الحي الثالث",
      isForSale: true,
      isFavorite: false,
      bedrooms: 3,
      bathrooms: 2,
      livingRooms: 1,
      floorNumber: 5,
      totalFloors: 10,
      hasElevator: true,
      hasParking: true,
      hasSecurity: true,
      hasBalcony: true,
    ),
    ApartmentDetails(
      title: "شقة للإيجار مفروشة",
      imagesUrl: ["https://cdn.britannica.com/05/157305-004-53D5D212.jpg"],
      area: 120,
      price: 8000,
      location: "الحي الأول",
      isForSale: false,
      isFavorite: false,
      bedrooms: 2,
      bathrooms: 1,
      livingRooms: 1,
      floorNumber: 2,
      totalFloors: 6,
      hasElevator: true,
      hasParking: false,
      hasSecurity: false,
      hasBalcony: true,
    ),
  ];

  static List<LandDetails> lands = [
    LandDetails(
      title: "أرض سكنية ناصية",
      imagesUrl: ["https://cdn.britannica.com/05/157305-004-53D5D212.jpg"],
      area: 300,
      price: 900000,
      location: "الحي الخامس",
      isForSale: true,
      isFavorite: false,
      zoning: "سكني",
      streetWidth: 15,
      isCorner: true,
      onMainStreet: true,
      hasWater: true,
      hasElectricity: true,
      hasSewage: true,
    ),
    LandDetails(
      title: "أرض تجارية على الطريق الرئيسي",
      imagesUrl: ["https://cdn.britannica.com/05/157305-004-53D5D212.jpg"],
      area: 500,
      price: 2000000,
      location: "المنطقة الصناعية",
      isForSale: true,
      isFavorite: true,
      zoning: "تجاري",
      streetWidth: 25,
      isCorner: false,
      onMainStreet: true,
      hasWater: true,
      hasElectricity: true,
      hasSewage: false,
    ),
  ];
}
